server:
    port : 1150

app:
    upload:
        path: images

spring:
    servlet:
        multipart:
            enabled: true
            max-file-size: 100MB
            max-request-size: 100MB
cloud:
    aws:
        credentials:
            access-key: 
            secret-key: 
        region:
            static: 
        stack:
            auto: false

application:
    bucket:
        name: 
---
spring:
    profiles:
        active: dev
---
spring:
    profiles: dev
    datasource:
        url: 
        username: 
        password: 

    jpa:
        properties:
            hibernate:
                format_sql: true
        show-sql: true
        hibernate.ddl-auto: update
---
spring:
    profiles: test
    datasource:
        url: 
        username: 
        password: 

    jpa:
        properties:
            hibernate:
                format_sql: true
        show-sql: true
        hibernate.ddl-auto: create-drop
    h2:
        console:
            enabled: true
---
spring:
    profiles: prod
    datasource:
        url: 
        username: 
        password: 
    jpa:
        hibernate.ddl-auto: update

server:
    port : 5000
---